# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('game_id', models.IntegerField()),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
