# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountId',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField()),
                ('game_club_id', models.IntegerField()),
                ('club_level', models.IntegerField()),
                ('club_name', models.CharField(max_length=20)),
                ('club_short_name', models.CharField(max_length=4)),
                ('water_rate', models.IntegerField()),
                ('insurance_rate', models.IntegerField()),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ClubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('remark', models.IntegerField(max_length=20)),
                ('note', models.CharField(max_length=100)),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_user_id', models.IntegerField()),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
        migrations.RenameField(
            model_name='gameuser',
            old_name='game_id',
            new_name='game_user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='game_id',
            new_name='game_user_id',
        ),
    ]
