# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0002_auto_20180309_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='remark',
            field=models.CharField(max_length=20),
        ),
    ]
