# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0003_auto_20180309_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubId',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_club_id', models.IntegerField()),
                ('club_name', models.CharField(max_length=20)),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactive_time', models.DateTimeField(default='2037-01-01')),
            ],
        ),
    ]
